Parameters:

    LambdaRoleArn:
        Type: String 
        Default: "YOUR_IAM_ROLE"

    LambdaImageUri:
        Type: String 
        Default: "ECR_Uri"
        
    Environment:
        Type: String 
        Default: "dev"

Resources:
    ContainerizedLambda:
        Type: AWS::Lambda::Function 
        Properties: 
            Code:
                ImageUri: !Ref LambdaImageUri
            Description: !Sub '${Environment} Lambda function to perform data processing'
            FunctionName: !Sub 'containerized-lambda-processdata-python-${Environment}'
            MemorySize: 3000 
            PackageType: "Image" 
            Role: !Ref LambdaRoleArn 
            Timeout: 900
