Parameters:

    LambdaRoleArn:
        Type: String 
        Default: "YOUR_IAM_ROLE"

    LambdaImageUri:
        Type: String 
        Default: "ECR_Uri"

Resources:
    ContainerizedLambda:
        Type: AWS::Lambda::Function 
        Properties: 
            Code:
                ImageUri: "#{BuildVariables.LAMBDA_IMAGE_URI}"
            Description: "PROD Lambda function to perform feature engineering" 
            FunctionName: "Containerized-Lambda-Demo" 
            MemorySize: 3000 
            PackageType: "Image" 
            Role: !Ref LambdaRoleArn 
            Timeout: 900
